### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-Luz1727#1]
[Infografia-LuzArleth.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-Luz1727/files/15471391/Infografia-LuzArleth.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificacion 20
